montgomery_thomas_tb.v:
	iverilog -o montgomery_thomas_tb.vvp montgomery_thomas_tb.v 
	vvp montgomery_thomas_tb.vvp 
	gtkwave tb_montgomery.vcd

clean:
	rm *.vvp 
	rm *.vcd

.PHONY: montgomery_thomas_tb.v